/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.analysis;

import minijava.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTLchave(TLchave node);
    void caseTRchave(TRchave node);
    void caseTLparen(TLparen node);
    void caseTRparen(TRparen node);
    void caseTLcolchete(TLcolchete node);
    void caseTRcolchete(TRcolchete node);
    void caseTSemicolon(TSemicolon node);
    void caseTVirgula(TVirgula node);
    void caseTIgual(TIgual node);
    void caseTIf(TIf node);
    void caseTElse(TElse node);
    void caseTWhile(TWhile node);
    void caseTClass(TClass node);
    void caseTPublic(TPublic node);
    void caseTStatic(TStatic node);
    void caseTVoid(TVoid node);
    void caseTMain(TMain node);
    void caseTExtends(TExtends node);
    void caseTIntf(TIntf node);
    void caseTInt(TInt node);
    void caseTBoolean(TBoolean node);
    void caseTReturn(TReturn node);
    void caseTPrint(TPrint node);
    void caseTTrue(TTrue node);
    void caseTFalse(TFalse node);
    void caseTTipo(TTipo node);
    void caseTBooleano(TBooleano node);
    void caseTOp(TOp node);
    void caseTNew(TNew node);
    void caseTThis(TThis node);
    void caseTVazio(TVazio node);
    void caseTIntegerLiteral(TIntegerLiteral node);
    void caseTLength(TLength node);
    void caseTPonto(TPonto node);
    void caseTString(TString node);
    void caseTExclamacao(TExclamacao node);
    void caseTId(TId node);
    void caseTTokIntegerlit(TTokIntegerlit node);
    void caseTReal(TReal node);
    void caseTWhitespace(TWhitespace node);
    void caseTComments(TComments node);
    void caseEOF(EOF node);
}
