/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.analysis;

import minijava.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAProgramProgram(AProgramProgram node);
    void caseAMainclassMainclass(AMainclassMainclass node);
    void caseAClassdeclClassdecl(AClassdeclClassdecl node);
    void caseAClassdecl(AClassdecl node);
    void caseAVardeclVardecl(AVardeclVardecl node);
    void caseAMethoddecl(AMethoddecl node);
    void caseAFormallistFormallist(AFormallistFormallist node);
    void caseAFormallist(AFormallist node);
    void caseAFormalrest(AFormalrest node);
    void caseAIntfType(AIntfType node);
    void caseABooleanType(ABooleanType node);
    void caseAIntType(AIntType node);
    void caseAIdType(AIdType node);
    void caseAStatementStatement(AStatementStatement node);
    void caseAIfStatement(AIfStatement node);
    void caseAWhileStatement(AWhileStatement node);
    void caseAPrintStatement(APrintStatement node);
    void caseAIgualStatement(AIgualStatement node);
    void caseAExpigualStatement(AExpigualStatement node);
    void caseAOpExp(AOpExp node);
    void caseAExpExp(AExpExp node);
    void caseALengthExp(ALengthExp node);
    void caseAExplistExp(AExplistExp node);
    void caseAIntliteralExp(AIntliteralExp node);
    void caseATrueExp(ATrueExp node);
    void caseAFalseExp(AFalseExp node);
    void caseAIdExp(AIdExp node);
    void caseAThisExp(AThisExp node);
    void caseANewintExp(ANewintExp node);
    void caseANewidExp(ANewidExp node);
    void caseAExclamacaoExp(AExclamacaoExp node);
    void caseAEntreparExp(AEntreparExp node);
    void caseAExprestExplist(AExprestExplist node);
    void caseAExplist(AExplist node);
    void caseAExprest(AExprest node);

    void caseTTkLchave(TTkLchave node);
    void caseTTkRchave(TTkRchave node);
    void caseTTkLparen(TTkLparen node);
    void caseTTkRparen(TTkRparen node);
    void caseTTkLcolchete(TTkLcolchete node);
    void caseTTkRcolchete(TTkRcolchete node);
    void caseTTkSemicolon(TTkSemicolon node);
    void caseTTkVirgula(TTkVirgula node);
    void caseTTkIgual(TTkIgual node);
    void caseTTkIf(TTkIf node);
    void caseTTkElse(TTkElse node);
    void caseTTkWhile(TTkWhile node);
    void caseTTkClass(TTkClass node);
    void caseTTkPublic(TTkPublic node);
    void caseTTkStatic(TTkStatic node);
    void caseTTkVoid(TTkVoid node);
    void caseTTkMain(TTkMain node);
    void caseTTkExtends(TTkExtends node);
    void caseTTkIntf(TTkIntf node);
    void caseTTkInt(TTkInt node);
    void caseTTkBoolean(TTkBoolean node);
    void caseTTkReturn(TTkReturn node);
    void caseTTkPrint(TTkPrint node);
    void caseTTkTrue(TTkTrue node);
    void caseTTkFalse(TTkFalse node);
    void caseTTkTipo(TTkTipo node);
    void caseTTkBooleano(TTkBooleano node);
    void caseTTkOp(TTkOp node);
    void caseTTkNew(TTkNew node);
    void caseTTkThis(TTkThis node);
    void caseTTkVazio(TTkVazio node);
    void caseTTkIntegerLiteral(TTkIntegerLiteral node);
    void caseTTkLength(TTkLength node);
    void caseTTkPonto(TTkPonto node);
    void caseTTkString(TTkString node);
    void caseTTkExclamacao(TTkExclamacao node);
    void caseTTkId(TTkId node);
    void caseTTkTokIntegerlit(TTkTokIntegerlit node);
    void caseTTkReal(TTkReal node);
    void caseTTkWhitespace(TTkWhitespace node);
    void caseTTkComments(TTkComments node);
    void caseEOF(EOF node);
}
