/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class TIntegerLiteral extends Token
{
    public TIntegerLiteral()
    {
        super.setText("integer_literal");
    }

    public TIntegerLiteral(int line, int pos)
    {
        super.setText("integer_literal");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIntegerLiteral(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIntegerLiteral(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TIntegerLiteral text.");
    }
}
