/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class TIntf extends Token
{
    public TIntf()
    {
        super.setText("int []");
    }

    public TIntf(int line, int pos)
    {
        super.setText("int []");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIntf(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIntf(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TIntf text.");
    }
}
