/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.lexer;

import java.io.*;
import minijava.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") PushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkLchave(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkRchave(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkLparen(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkRparen(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkLcolchete(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkRcolchete(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkSemicolon(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkVirgula(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkIgual(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkIf(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkElse(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkWhile(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkClass(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkPublic(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkStatic(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkVoid(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkMain(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkExtends(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkIntf(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkInt(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkBoolean(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkReturn(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkPrint(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkTrue(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkFalse(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkTipo(line, pos); }
    Token new26(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkBooleano(text, line, pos); }
    Token new27(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkOp(text, line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkNew(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkThis(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkVazio(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkIntegerLiteral(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkLength(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkPonto(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkString(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkExclamacao(line, pos); }
    Token new36(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkId(text, line, pos); }
    Token new37(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkTokIntegerlit(text, line, pos); }
    Token new38(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkReal(text, line, pos); }
    Token new39(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkWhitespace(text, line, pos); }
    Token new40(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTkComments(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {38, 38, 6}, {40, 40, 7}, {41, 41, 8}, {42, 42, 9}, {43, 43, 10}, {44, 44, 11}, {45, 45, 12}, {46, 46, 13}, {47, 47, 14}, {48, 57, 15}, {59, 59, 16}, {60, 60, 17}, {61, 61, 18}, {63, 63, 19}, {65, 82, 20}, {83, 83, 21}, {84, 90, 20}, {91, 91, 22}, {93, 93, 23}, {97, 97, 24}, {98, 98, 25}, {99, 99, 26}, {100, 100, 24}, {101, 101, 27}, {102, 102, 28}, {103, 104, 24}, {105, 105, 29}, {106, 107, 24}, {108, 108, 30}, {109, 109, 31}, {110, 110, 32}, {111, 111, 24}, {112, 112, 33}, {113, 113, 24}, {114, 114, 34}, {115, 115, 35}, {116, 116, 36}, {117, 117, 24}, {118, 118, 37}, {119, 119, 38}, {120, 122, 24}, {123, 123, 39}, {125, 125, 40}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {},
            {{38, 38, 41}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {{48, 57, 42}, },
            {{42, 42, 43}, {47, 47, 44}, },
            {{46, 46, 45}, {48, 57, 15}, },
            {},
            {},
            {},
            {},
            {{48, 57, 46}, {65, 90, 47}, {95, 95, 48}, {97, 122, 49}, },
            {{48, 95, -22}, {97, 120, 49}, {121, 121, 50}, {122, 122, 49}, },
            {},
            {},
            {{48, 122, -22}, },
            {{48, 95, -22}, {97, 110, 49}, {111, 111, 51}, {112, 122, 49}, },
            {{48, 95, -22}, {97, 107, 49}, {108, 108, 52}, {109, 122, 49}, },
            {{48, 107, -28}, {108, 108, 53}, {109, 119, 49}, {120, 120, 54}, {121, 122, 49}, },
            {{48, 95, -22}, {97, 97, 55}, {98, 122, 49}, },
            {{48, 95, -22}, {97, 101, 49}, {102, 102, 56}, {103, 109, 49}, {110, 110, 57}, {111, 122, 49}, },
            {{48, 95, -22}, {97, 100, 49}, {101, 101, 58}, {102, 122, 49}, },
            {{48, 95, -22}, {97, 97, 59}, {98, 122, 49}, },
            {{48, 100, -32}, {101, 101, 60}, {102, 122, 49}, },
            {{48, 95, -22}, {97, 116, 49}, {117, 117, 61}, {118, 122, 49}, },
            {{48, 100, -32}, {101, 101, 62}, {102, 122, 49}, },
            {{48, 95, -22}, {97, 115, 49}, {116, 116, 63}, {117, 122, 49}, },
            {{48, 95, -22}, {97, 103, 49}, {104, 104, 64}, {105, 113, 49}, {114, 114, 65}, {115, 120, 49}, {121, 121, 66}, {122, 122, 49}, },
            {{48, 110, -27}, {111, 111, 67}, {112, 122, 49}, },
            {{48, 103, -38}, {104, 104, 68}, {105, 122, 49}, },
            {},
            {},
            {},
            {{48, 57, 42}, },
            {{0, 41, 69}, {42, 42, 70}, {43, 65535, 69}, },
            {{0, 9, 71}, {10, 10, 72}, {11, 12, 71}, {13, 13, 73}, {14, 65535, 71}, },
            {{48, 57, 74}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 95, -22}, {97, 114, 49}, {115, 115, 75}, {116, 122, 49}, },
            {{48, 110, -27}, {111, 111, 76}, {112, 122, 49}, },
            {{48, 95, -22}, {97, 97, 77}, {98, 122, 49}, },
            {{48, 114, -52}, {115, 115, 78}, {116, 122, 49}, },
            {{48, 115, -37}, {116, 116, 79}, {117, 122, 49}, },
            {{48, 107, -28}, {108, 108, 80}, {109, 122, 49}, },
            {{48, 122, -22}, },
            {{48, 115, -37}, {116, 116, 81}, {117, 122, 49}, },
            {{48, 95, -22}, {97, 109, 49}, {110, 110, 82}, {111, 122, 49}, },
            {{48, 95, -22}, {97, 104, 49}, {105, 105, 83}, {106, 122, 49}, },
            {{48, 95, -22}, {97, 118, 49}, {119, 119, 84}, {120, 122, 49}, },
            {{48, 95, -22}, {97, 97, 49}, {98, 98, 85}, {99, 122, 49}, },
            {{48, 115, -37}, {116, 116, 86}, {117, 122, 49}, },
            {{48, 95, -22}, {97, 97, 87}, {98, 113, 49}, {114, 114, 88}, {115, 122, 49}, },
            {{48, 104, -61}, {105, 105, 89}, {106, 122, 49}, },
            {{48, 116, -35}, {117, 117, 90}, {118, 122, 49}, },
            {{48, 95, -22}, {97, 111, 49}, {112, 112, 91}, {113, 122, 49}, },
            {{48, 104, -61}, {105, 105, 92}, {106, 122, 49}, },
            {{48, 104, -61}, {105, 105, 93}, {106, 122, 49}, },
            {{0, 65535, -45}, },
            {{0, 42, -45}, {43, 46, 69}, {47, 47, 94}, {48, 65535, 69}, },
            {{0, 65535, -46}, },
            {{13, 13, 95}, },
            {},
            {{48, 57, 74}, },
            {{48, 115, -37}, {116, 116, 96}, {117, 122, 49}, },
            {{48, 107, -28}, {108, 108, 97}, {109, 122, 49}, },
            {{48, 114, -52}, {115, 115, 98}, {116, 122, 49}, },
            {{48, 100, -32}, {101, 101, 99}, {102, 122, 49}, },
            {{48, 100, -32}, {101, 101, 100}, {102, 122, 49}, },
            {{48, 114, -52}, {115, 115, 101}, {116, 122, 49}, },
            {{32, 32, 102}, {48, 100, -32}, {101, 101, 103}, {102, 122, 49}, },
            {{48, 95, -22}, {97, 102, 49}, {103, 103, 104}, {104, 122, 49}, },
            {{48, 109, -60}, {110, 110, 105}, {111, 122, 49}, },
            {{48, 122, -22}, },
            {{48, 107, -28}, {108, 108, 106}, {109, 122, 49}, },
            {{48, 116, -35}, {117, 117, 107}, {118, 122, 49}, },
            {{48, 115, -37}, {116, 116, 108}, {117, 122, 49}, },
            {{48, 104, -61}, {105, 105, 109}, {106, 122, 49}, },
            {{48, 114, -52}, {115, 115, 110}, {116, 122, 49}, },
            {{48, 100, -32}, {101, 101, 111}, {102, 122, 49}, },
            {{48, 100, -32}, {101, 101, 112}, {102, 122, 49}, },
            {{48, 95, -22}, {97, 99, 49}, {100, 100, 113}, {101, 122, 49}, },
            {{48, 107, -28}, {108, 108, 114}, {109, 122, 49}, },
            {{0, 65535, -45}, },
            {},
            {{48, 100, -32}, {101, 101, 115}, {102, 122, 49}, },
            {{48, 100, -32}, {101, 101, 116}, {102, 122, 49}, },
            {{48, 114, -52}, {115, 115, 117}, {116, 122, 49}, },
            {{48, 122, -22}, },
            {{48, 109, -60}, {110, 110, 118}, {111, 122, 49}, },
            {{48, 100, -32}, {101, 101, 119}, {102, 122, 49}, },
            {{91, 91, 120}, },
            {{48, 102, -84}, {103, 103, 121}, {104, 122, 49}, },
            {{48, 115, -37}, {116, 116, 122}, {117, 122, 49}, },
            {{48, 122, -22}, },
            {{48, 104, -61}, {105, 105, 123}, {106, 122, 49}, },
            {{48, 95, -22}, {97, 113, 49}, {114, 114, 124}, {115, 122, 49}, },
            {{48, 104, -61}, {105, 105, 125}, {106, 122, 49}, },
            {{48, 109, -60}, {110, 110, 126}, {111, 122, 49}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 100, -32}, {101, 101, 127}, {102, 122, 49}, },
            {{48, 95, -22}, {97, 108, 49}, {109, 109, 128}, {110, 122, 49}, },
            {{48, 95, -22}, {97, 97, 129}, {98, 122, 49}, },
            {{48, 122, -22}, },
            {{48, 99, -94}, {100, 100, 130}, {101, 122, 49}, },
            {{48, 122, -22}, },
            {{93, 93, 131}, },
            {{48, 100, -32}, {101, 101, 132}, {102, 122, 49}, },
            {{48, 103, -38}, {104, 104, 133}, {105, 122, 49}, },
            {{48, 95, -22}, {97, 98, 49}, {99, 99, 134}, {100, 122, 49}, },
            {{48, 109, -60}, {110, 110, 135}, {111, 122, 49}, },
            {{48, 98, -125}, {99, 99, 136}, {100, 122, 49}, },
            {{48, 102, -84}, {103, 103, 137}, {104, 122, 49}, },
            {{48, 122, -22}, },
            {{46, 46, 138}, {48, 122, -22}, },
            {{48, 109, -60}, {110, 110, 139}, {111, 122, 49}, },
            {{48, 114, -52}, {115, 115, 140}, {116, 122, 49}, },
            {},
            {{48, 113, -109}, {114, 114, 141}, {115, 122, 49}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{111, 111, 142}, },
            {{48, 122, -22}, },
            {{48, 122, -22}, },
            {{48, 90, -22}, {95, 95, 143}, {97, 122, 49}, },
            {{117, 117, 144}, },
            {{48, 107, -28}, {108, 108, 145}, {109, 122, 49}, },
            {{116, 116, 146}, },
            {{48, 104, -61}, {105, 105, 147}, {106, 122, 49}, },
            {{46, 46, 148}, },
            {{48, 115, -37}, {116, 116, 149}, {117, 122, 49}, },
            {{112, 112, 150}, },
            {{48, 100, -32}, {101, 101, 151}, {102, 122, 49}, },
            {{114, 114, 152}, },
            {{48, 113, -109}, {114, 114, 153}, {115, 122, 49}, },
            {{105, 105, 154}, },
            {{48, 95, -22}, {97, 97, 155}, {98, 122, 49}, },
            {{110, 110, 156}, },
            {{48, 107, -28}, {108, 108, 157}, {109, 122, 49}, },
            {{116, 116, 158}, },
            {{48, 122, -22}, },
            {{108, 108, 159}, },
            {{110, 110, 160}, },
            {},
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 39, 39, 39, 39, 35, -1, 2, 3, 27, 27, 7, 27, 33, -1, 37, 6, 27, 8, 30, 36, 36, 4, 5, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 0, 1, 27, 38, -1, -1, 38, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 9, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, -1, -1, -1, 40, 40, 38, 36, 36, 36, 36, 36, 36, 19, 36, 36, 28, 36, 36, 36, 36, 36, 36, 36, 36, 36, 40, 40, 36, 36, 36, 10, 36, 36, -1, 36, 36, 16, 36, 36, 36, 36, 29, 23, 25, 15, 36, 36, 36, 12, 36, 24, -1, 36, 36, 36, 36, 36, 36, 11, 36, 36, 36, 18, 36, 32, 13, 21, 14, 34, -1, 20, 17, 36, -1, 36, -1, 36, -1, 36, -1, 36, -1, 36, -1, 36, -1, 36, -1, 31, -1, -1, 22, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
